### ISSUE TITLE
9 - Seat Reservation Service not implemented

### ISSUE THREAD

**Issue by bchewy** [bchewy/bolabola#15]
Seat Reservation Service not implemented

#### seat reservation schema
userid, matchid, ticketcat, ticketid, 
-, 1, A, 1 
-, 1, C, 3
-, 1, A, 2

When the user proceeds to pay for a ticket, seat reservation service:  userid is updated, and ticketID is on a redis hold, 
When the user proceeds to pay for a ticket, match crud service:  seatqty -1
When the redis TTL holds ends and user did not buy ticket, we need to update match crud + ticket reservation to null the userid

#### match crud 
matchid, seatqty
1,3

**Comment by yijiyap** [comment]
ronaldo sewy
