### ISSUE TITLE
4 - User Profile Service not implemented

### ISSUE THREAD

**Issue by bchewy** [bchewy/bolabola#16]
The User Profile Service will be able to perform the following functionalities:

Purchasing of Ticket
Upon user checkout, the service is responsible for consuming messages from a RabbitMQ queue. Subsequently, it updates the user's ticket information in the user profile and adds the invoice to the user's purchase history.

Retrieve all tickets under user
The service facilitates retrieving all tickets associated with a specific user by utilizing the user ID. This functionality is achieved through an HTTP GET request to fetch relevant ticket data stored in the database.

Refund Ticket
After the approval of a ticket refund, the service will utilize AMQP to retrieve messages from a RabbitMQ queue. Subsequently, it will proceed to remove the corresponding ticket from the user's account stored in the database.

**Comment by yijiyap** [comment]
boooom ez
