### ISSUE TITLE
6 - Live Match Service is not implemented

### ISSUE THREAD

**Issue by bchewy** [bchewy/bolabola#25]
The Live Match Stats Service is a real-time data processing microservice designed to provide users with live statistics during match playbacks.

It listens for incoming websocket connections from the Match Streaming UI.

Upon receiving a match ID and timestamp, it fetches relevant live data from the Match Stats Database, which is structured to efficiently serve time-series data for sporting events.

**Match Stats Database (InfluxDB)**: This time-series database stores the statistics for matches, which are queried by the Live Match Stats Service.

**Comment by yijiyap** [comment]
gg
